### PR TITLE
missing guid for device.

### PR DESCRIPTION
**Pull request by ferdna**
this will fix compiling error of QStlink2. https://pastebin.com/nr3Hik4H

### CODE REVIEW

**Comment by ferdna** [comment]
maybe we can add "filter.guid = desc.GUID;" to qlibusb.cpp line 38. I couldn't find anything that resembles a GUID in libusb_device_descriptor. maybe you know what to do. I leave it to you.

https://pastebin.com/uBrBD2w6

**Comment by ferdna** [comment]
sorry I just read the code and modifying qlibusb.cpp is not necessary since the GUID is assigned on object creation in lines 35 & 40 in stlinkv2.cpp in the QStlink2 project.

**Comment by fpoussin** [comment]
Can you check the submodules are checked out in QSTlink2? There are multiple branches for QtUSB.

I need to check again but that should be fine.

**Comment by ferdna** [comment]
you are right. just cloned master and there is no GUID error. I am running latest release which is: 1.2.3

**Pull request closed without merging**
